In [1]:
import numpy as np

## Generating 1D array

In [15]:
p  = np.array([1, 2, 3, 4, 5, 6, 7,8, 9])

In [16]:
p

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## Generating 2D array

In [12]:
b  = np.array([[1, 2],[3, 4], [5, 6], [7,8]])

In [13]:
b

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [9]:
a  = np.array([[1, 2,3],[ 4, 5, 6], [7,8, 9]])

In [10]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
a. shape

(3, 3)

In [14]:
b.shape

(4, 2)

In [17]:
p.shape

(9,)

In [20]:
type(a)

numpy.ndarray

In [21]:
type(b)

numpy.ndarray

In [22]:
type(p)

numpy.ndarray

In [23]:
a.dtype

dtype('int64')

In [24]:
b.dtype

dtype('int64')

In [26]:
p.dtype

dtype('int64')

## **Maximum and Minimum values of array**

In [28]:
np.max(a), np.max(b), np.max(p)

(9, 8, 9)

In [29]:
np.min(a), np.min(b), np.min(p)

(1, 1, 1)

## **Index of Maximum and minimum values**

In [30]:
a = np.array([1, 45, 4, 67, 78, 23, 14])

In [31]:
a

array([ 1, 45,  4, 67, 78, 23, 14])

In [32]:
np.max(a)

78

In [33]:
a.max()

78

In [34]:
a.argmax()

4

In [35]:
a.argmin()

0

In [36]:
a.min()

1

## **Arange**

In [37]:
c = np.array([0, 1, 2, 3, 4, 5,6,7, 8,9])

In [38]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### So, It's very time consuming process. For that, arange can be used.

In [47]:
c = np.arange(0,10,1)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
c = np.arange(0,100) #default interval = 1
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [51]:
d = np.arange(0, 10, 2)
d

array([0, 2, 4, 6, 8])

In [53]:
e  = np.arange(0, 100, 20)
e

array([ 0, 20, 40, 60, 80])

## **LinSpace** (Lineraly Spaced Number)

In [55]:
x1 = np.linspace(0, 20, 5)
x1

array([ 0.,  5., 10., 15., 20.])

In [56]:
x2 = np.linspace(0, 10, 3)
x2

array([ 0.,  5., 10.])

In [58]:
x3 = np.linspace(0, 10, 50)
x3

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [59]:
x3.shape

(50,)

## **Reshape** (For converting 1D array to 2D array)

In [60]:
y = np.arange(0, 25)

In [61]:
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [62]:
y.shape

(25,)

In [63]:
y.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [65]:
y.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [66]:
y.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [68]:
y.reshape(3,3)

ValueError: cannot reshape array of size 25 into shape (3,3)

### Error is coming because 25 elements are there. But, 3 * 3 = 9 elements can't be chosen.

In [69]:
y.reshape(5,6)

ValueError: cannot reshape array of size 25 into shape (5,6)

### Error is coming because 25 elements are there in original array. But, 5 * 6 = 30 elements can't be chosen.

## **Zeros and Ones**

In [70]:
np.zeros(3)

array([0., 0., 0.])

In [71]:
np.zeros(shape=[3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [72]:
np.zeros(shape=[3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [73]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [76]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### Now we can generate any matrix by multiplying

In [77]:
7 * np.ones((3,3))

array([[7., 7., 7.],
       [7., 7., 7.],
       [7., 7., 7.]])

## **Eye - Generating Identity Matrix**

### For Identity matrix all diagonal elements are 1. Rest elements are all zero

In [78]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [79]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## **Random Numbers**

### **1. Randn - generates random numbers from normal distribution**

In [81]:
x1 = np.random.randn(3,3)
x1

array([[ 1.25547962, -0.69855671,  1.28085191],
       [-1.57329372,  0.69896532,  0.06637472],
       [ 0.70647094, -0.65260759, -1.44543348]])

### **2. Rand - Generates random numbers between 0 & 1**

In [83]:
x2 = np.random.rand(4,5)
x2

array([[0.61201712, 0.99113182, 0.33834218, 0.9856546 , 0.69529098],
       [0.1414718 , 0.6192212 , 0.84886612, 0.40061481, 0.54950903],
       [0.7280056 , 0.52244046, 0.18259628, 0.2474309 , 0.87517857],
       [0.91416269, 0.18530621, 0.41041156, 0.43421326, 0.18965569]])

### 3. **Randint - will generate random integers between given range**

In [84]:
x3 = np.random.randint(3, 8, 10)
x3

array([6, 3, 3, 7, 3, 4, 3, 4, 6, 4])

## **Indexing and Slicing**

### **Indexing and Slicing in 1D array**

In [88]:
ar = np.array([4, 2, 33, 14, 13, 6, 7, 14])
ar

array([ 4,  2, 33, 14, 13,  6,  7, 14])

In [90]:
ar[3] #indexing - extracting only one number

14

In [97]:
ar[0:5]

array([ 4,  2, 33, 14, 13])

In [96]:
ar[1:3] #slicing - extracting multiple numbers

array([ 2, 33])

In [93]:
ar[-1] # Extracting last number of the array

14

In [95]:
ar[-2] # Extracting second last number of the array

7

In [98]:
ar[1:]

array([ 2, 33, 14, 13,  6,  7, 14])

In [99]:
ar[:4]

array([ 4,  2, 33, 14])

In [104]:
ar[:-1] # include everything except the last number of the array

array([ 4,  2, 33, 14, 13,  6,  7])

In [101]:
ar[::-1] #Reversing or flipping the array

array([14,  7,  6, 13, 14, 33,  2,  4])

### **Indexing of Sub-array & Sub-matrix from 2D (matrix) array**

In [105]:
arr = np.arange(1, 17).reshape(4,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
arr[0] #Extracting first row

array([1, 2, 3, 4])

In [108]:
arr[3] #Extracting last row

array([13, 14, 15, 16])

In [109]:
arr[2][1]

10

In [110]:
arr[2,1]# other method

10

In [114]:
arr[1:3,1:3] #Extracting sub-matrix

array([[ 6,  7],
       [10, 11]])

In [113]:
arr[:,3] # Extracting last column

array([ 4,  8, 12, 16])

In [121]:
arr[:,3].reshape(-1,1) #Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])

In [118]:
arr[:,3:]#other way for Extracting last column vertically

array([[ 4],
       [ 8],
       [12],
       [16]])